---
name: 🐛 Bug Report
about: Create a report to help us improve
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: ''

---

## 🐛 Bug Description

A clear and concise description of what the bug is.

## 🔄 Steps to Reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## ✅ Expected Behavior

A clear and concise description of what you expected to happen.

## ❌ Actual Behavior

A clear and concise description of what actually happened.

## 📷 Screenshots

If applicable, add screenshots to help explain your problem.

## 🖥️ Environment

**System Information:**
- OS: [e.g., Ubuntu 20.04, Windows 10, macOS 12]
- Python version: [e.g., 3.9.7]
- Package version: [e.g., 1.0.1]
- Installation method: [pip, conda, source]

**Dependencies:**
```bash
# Run this command and paste the output
fingermatcher version
python -c "import advance_fingermatcher; advance_fingermatcher.print_system_info()"
```

## 📋 Additional Context

Add any other context about the problem here.

## 🔍 Error Output

If applicable, paste the full error traceback:

```
Paste error output here
```

## ✨ Possible Solution

If you have ideas on how to fix this, please describe them here.

## 📚 Related Issues

Link any related issues here using #issue_number
